### Get all
GET http://localhost:3000/api/messages

### Get single
GET http://localhost:3000/api/user:anvId

### Create new
POST http://localhost:3000/api

###Signup Create user
POST  http://localhost:3000/api/users
Content-Type: application/json; charset=utf-8

{
     "email":"asrinne@hej.se",
     "password": "hej123",
     "nickname": "Asrinne"
}

### Message
POST  http://localhost:3000/api/message
Content-Type: application/json; charset=utf-8

{
     "message": "hallihallå",
     "userId": 2
}

